"""
This script provides the functions to calculate the geometry of a fuel grain and the needed outputs:
    Port area, Burning area, Chamber volume
"""
import numpy as np
import matplotlib.pyplot as plt

def plot_polygon(x, y, title=None):
    """
    Plots a polygon. Generated by Copilot.
    :param x:
    :param y:
    :param title:
    :return:
    """
    x = np.asarray(x); y = np.asarray(y)
    plt.figure(figsize=(5,5))
    plt.plot(np.r_[x, x[0]], np.r_[y, y[0]], '-o')
    plt.axhline(0, color='k', linewidth=0.5)
    plt.axvline(0, color='k', linewidth=0.5)
    plt.gca().set_aspect('equal', 'box')
    if title:
        plt.title(title)
    plt.show()

def is_between(value, a, b):
    """
    Support function for checking if a value is between a and b
    :param value: value to check
    :param a: first side
    :param b: second side
    :return: Boolean
    """
    start = min([a, b])
    end = max([a, b])

    result = (value >= start and value <= end)
    return result

def create_regular_poligon(n_sides, circum_radius):
    """
    Generates a regular poligon inscripted in the circumference.
    :param n_sides: Number of sides
    :param circum_radius: Radius of circumscribed circonference
    :return: x_poly, y_poly
    """
    theta = 2 * np.pi / n_sides
    thetas = np.arange(0, n_sides, 1)
    thetas = thetas * theta
    x_poly = circum_radius * np.cos(thetas)
    y_poly = circum_radius * np.sin(thetas)
    return x_poly, y_poly

def create_repeated_instance(x, y, n_instances):
    """
    Given the points, repeats an instance around the origin for the given number.
    It also removes the points sharing the same location.
    :param x: x-axis points
    :param y: y-axis points
    :param n_instances: number of instances to repeat
    :return: x_u, y_u
    """
    theta = 2 * np.pi / n_instances
    thetas = np.arange(0, n_instances, 1) * theta

    angles = np.arctan2(y, x)
    radius = np.hypot(x, y)

    angles_rep = []
    radius_rep = []
    for i in range(n_instances):
        angles_rep.append(thetas[i]+angles)
        radius_rep.append(radius)

    angles_rep = np.array(angles_rep).ravel()
    radius_rep = np.array(radius_rep).ravel()

    x_rep = radius_rep * np.cos(angles_rep)
    y_rep = radius_rep * np.sin(angles_rep)

    pts = np.vstack((x_rep, y_rep)).T
    _, idx = np.unique(pts, axis=0, return_index=True)
    idx_sorted = np.sort(idx)
    pts_unique_in_order = pts[idx_sorted]
    x_u, y_u = pts_unique_in_order[:, 0], pts_unique_in_order[:, 1]

    return x_u, y_u

def translate_figure(x, y):
    """
    This function is used to translate the figure coordinates to have the origin inside it.
    :param x: np.array of x values
    :param y: np.array of y values
    :return: x_translated, y_translated
    """
    xG = np.sum(x) / np.size(x)
    yG = np.sum(y) / np.size(y)

    x_translated = x - xG
    y_translated = y - yG
    return x_translated, y_translated

def sort_input(x, y, z=1):
    """
    This function sorts the (x, y) inputs to be couterclock-wise or clock-wise depending on z.
    Use it carefully because it may change the desired geometry.
    :param x: np.array of x values
    :param y: np.array of y values
    :param z: z=1 counterclock, z=-1 clockwise
    :return: x_sorted, y_sorted
    """
    thetas = np.atan2(y, x)
    thetas[thetas < 0] += 2 * np.pi

    thetas = thetas * z
    sorted_indices = np.argsort(thetas)
    x_sorted = x[sorted_indices]
    y_sorted = y[sorted_indices]
    return x_sorted, y_sorted

def fill_borders(x, y, n_points_per_side):
    """
    Linear fill between (x, y) points.
    :param x: x-axis points
    :param y: y-axis points
    :param n_points_per_side: number of points between every x and y
    :return: x_fill, y_fill
    """
    x2 = np.r_[x, x[0]]
    y2 = np.r_[y, y[0]]

    x1 = x2[1:]
    y1 = y2[1:]

    t = np.linspace(0, 1, n_points_per_side + 1)[:-1]
    dx = (x1 - x)[:, None]  # (N,1)
    dy = (y1 - y)[:, None]  # (N,1)
    xs = x[:, None] + dx * t[None, :]  # (N,k)
    ys = y[:, None] + dy * t[None, :]  # (N,k)

    x_fill = xs.ravel()
    y_fill = ys.ravel()

    return x_fill, y_fill

def fill_borders_circumference(x, y, n_points_per_side):
    """
    Circular fill between (x, y) points if they have the same radius, or linear fill otherwise.
    :param x: x-axis points
    :param y: y-axis points
    :param n_points_per_side: number of points between every x and y
    :return: x_fill, y_fill
    """
    try:
        x2 = np.r_[x, x[0]]
        y2 = np.r_[y, y[0]]
    except IndexError:
        x2 = np.r_[x, x]
        y2 = np.r_[y, y]

    x0 = x2[:-1]
    y0 = y2[:-1]
    x1 = x2[1:]
    y1 = y2[1:]

    t = np.linspace(0, 1, n_points_per_side + 1)[:-1]
    dx = (x1 - x)[:, None]  # (N,1)
    dy = (y1 - y)[:, None]  # (N,1)

    r0 = np.hypot(x0, y0)
    r1 = np.hypot(x1, y1)
    same_r = np.isclose(r0, r1, atol=1e-12)

    theta0 = np.arctan2(y0, x0)  # (-pi, pi]
    theta1 = np.arctan2(y1, x1)
    delta = theta1 - theta0

    delta = (delta + np.pi) % (2.0 * np.pi) - np.pi

    # Fix: handle case where all deltas are zero (full circle)
    # Replace zeros with 2*pi for circular interpolation
    delta = np.where(np.isclose(delta, 0, atol=1e-12), 2 * np.pi, delta)

    t_row = t[None, :]  # (1,k)

    xs_lin = x0[:, None] + dx * t_row
    ys_lin = y0[:, None] + dy * t_row

    r0_col = r0[:, None]
    theta0_col = theta0[:, None]
    delta_col = delta[:, None]
    thetas = theta0_col + delta_col * t_row  # (N,k)
    xs_circ = r0_col * np.cos(thetas)
    ys_circ = r0_col * np.sin(thetas)

    mask = same_r[:, None]  # (N,1) broadcastable
    xs_block = np.where(mask, xs_circ, xs_lin)
    ys_block = np.where(mask, ys_circ, ys_lin)

    x_fill = xs_block.ravel()
    y_fill = ys_block.ravel()

    return x_fill, y_fill

def calculate_surfaces_from_points(x, y, lc, step=0.0):
    """
    This function calculates port area and burning area of a fuel grain, given the section points and the length.
    If step is different from zero, it calculates the burning area of a swirled grain.
    Burning area calculation has some uncertainties, an efficiency based on observations was developed.
    :param x: np.array of x values [m]
    :param y: np.array of y values [m]
    :param lc: Grain length [m]
    :param step: Helix step [m]
    :return: Port_area [m^2], Burning_area [m^2]
    """

    r = np.hypot(x, y)

    x2 = np.r_[x, x[0]]
    y2 = np.r_[y, y[0]]
    r2 = np.r_[r, r[0]]

    dx = np.diff(x2)
    dy = np.diff(y2)

    a = r2[:-1] # (a) side of the triangle formed by two points and the origin
    b = r2[1:] # (b) side of the triangle formed by two points and the origin
    c = np.hypot(dx, dy) # (c) side of the triangle formed by two points and the origin

    p = (a + b + c) / 2

    area_term = p * (p - a) * (p - b) * (p - c)
    area_term[area_term < 0] = 0.0
    areas = np.sqrt(area_term)  # Erone di Alessandria
    PortArea = np.sum(areas)

    perimeter = np.sum(c)
    if step == 0.0:
        BurningArea = perimeter * lc
    else:
        #Kerr = 0.2*0.1*2*np.pi/(0.96*16) # from observations
        #rend = 1 - Kerr * perimeter / step
        #Kerr = 0.2 * 0.1 / (2 * np.sqrt(2)) # from observations
        #rend = 1 - 0.908 * Kerr * np.max(r) / step
        #print(rend)

        h = min(np.min(c), step) / 10

        dtheta = h * 360 / step
        n_step = lc / h

        thetas = np.atan2(y, x) + np.deg2rad(dtheta)
        xT = r * np.cos(thetas)
        yT = r * np.sin(thetas)
        s = np.abs(dx*yT - dy*xT + dy*x - dx*y) / np.hypot(dx, dy)

        H = np.hypot(h, s)

        BurningArea = n_step * np.sum(H * c)

    return PortArea, BurningArea

def fill_and_calculate_surfaces_and_volume(x, y, lc, n_pointsperside=20, circular=False,
                                           step=0.0, Vol_prechamber=0.0, Vol_postchamber=0.0):
    """
    Helper function for mission simulation: fills the points and calculates the geometry values needed.
    :param x: x-values [m]
    :param y: y_values [m]
    :param lc: Chamber-length [m]
    :param n_pointsperside: points per side to fill every space between points
    :param circular: Bool
    :param step: helix step [m]
    :param Vol_prechamber: Prechamber volume [m^3]
    :param Vol_postchamber: Postchamber volume [m^3]
    :return: A_port: Port Area [m^2],
             A_burn: Burning Area [m^2],
             Vol_chamber: Chamber volume [m^3]
    """
    if circular:
        x_fill, y_fill = fill_borders_circumference(x,y,n_pointsperside)
    else:
        x_fill, y_fill = fill_borders(x,y,n_pointsperside)

    A_port, A_burn = calculate_surfaces_from_points(x_fill, y_fill, lc, step)

    Vol_chamber = (A_port * lc) + Vol_prechamber + Vol_postchamber

    return A_port, A_burn, Vol_chamber

def calculate_fuel_mass(Ap, lc, D_chamber, fuel_density):
    """
    Helper function for mission simulation: calculates the fuel mass considering remaining volume.
    :param Ap: Port Area [m^2]
    :param lc: Chamber-length [m]
    :param D_chamber: Maximum chamber diameter [m]
    :param fuel_density: Fuel density [kg/m^3]
    :return: mfuel: Fuel mass [kg]
    """
    empty_volume = Ap * lc
    full_volume = 0.25 * np.pi * (D_chamber**2) * lc
    remaining_volume = full_volume - empty_volume
    mfuel = remaining_volume * fuel_density

    return mfuel

if __name__ == '__main__':
    Ap, Ab, Vol = fill_and_calculate_surfaces_and_volume(np.array([0.03]), np.array([0.0]), 1, 20, True)

    print(Ap, Ab, Vol)

# end of file