"""
This script provides the functions to calculate the geometry of a fuel grain and the needed outputs:
    Port area, Burning area, Chamber volume
"""
import numpy as np
import matplotlib.pyplot as plt

def plot_polygon(x, y, title=None):
    """
    Plots a polygon. Generated by Copilot.
    :param x:
    :param y:
    :param title:
    :return:
    """
    x = np.asarray(x); y = np.asarray(y)
    plt.figure(figsize=(5,5))
    plt.plot(np.r_[x, x[0]], np.r_[y, y[0]], '-o')
    plt.axhline(0, color='k', linewidth=0.5)
    plt.axvline(0, color='k', linewidth=0.5)
    plt.gca().set_aspect('equal', 'box')
    if title:
        plt.title(title)
    plt.show()

def translate_figure(x, y):
    """
    This function is used to translate the figure coordinates to have the origin inside it.
    :param x: np.array of x values
    :param y: np.array of y values
    :return: x_translated, y_translated
    """
    xG = np.sum(x) / np.size(x)
    yG = np.sum(y) / np.size(y)

    x_translated = x - xG
    y_translated = y - yG
    return x_translated, y_translated

def sort_input(x, y):
    """
    This function sorts the (x, y) inputs to be couterclock-wise.
    :param x: np.array of x values
    :param y: np.array of y values
    :return: x_sorted, y_sorted
    """
    thetas = np.atan2(y, x)
    thetas[thetas < 0] += 2 * np.pi

    sorted_indices = np.argsort(thetas)
    x_sorted = x[sorted_indices]
    y_sorted = y[sorted_indices]
    return x_sorted, y_sorted

def fill_borders(x, y, n_points_per_side):
    x2 = np.r_[x, x[0]]
    y2 = np.r_[y, y[0]]

    x1 = x2[1:]
    y1 = y2[1:]

    t = np.linspace(0, 1, n_points_per_side + 1)[:-1]
    # calcoli broadcast: xs, ys shape (N, k)
    dx = (x1 - x)[:, None]  # (N,1)
    dy = (y1 - y)[:, None]  # (N,1)
    xs = x[:, None] + dx * t[None, :]  # (N,k)
    ys = y[:, None] + dy * t[None, :]  # (N,k)

    x_fill = xs.ravel()
    y_fill = ys.ravel()

    return x_fill, y_fill


def calculate_surfaces_from_points(x, y, lc, step=0.0):
    """
    This function calculates port area and burning area of a fuel grain, given the section points and the length.
    If step is different from zero, it calculates the burning area of a swirled grain.
    Burning area calculation has some uncertainties, an efficiency based on observations was developed.
    :param x: np.array of x values [m]
    :param y: np.array of y values [m]
    :param lc: Grain length [m]
    :param step: Helix step [m]
    :return: Port_area [m^2], Burning_area [m^2]
    """

    r = np.hypot(x, y)

    x2 = np.r_[x, x[0]]
    y2 = np.r_[y, y[0]]
    r2 = np.r_[r, r[0]]

    dx = np.diff(x2)
    dy = np.diff(y2)

    a = r2[:-1] # (a) side of the triangle formed by two points and the origin
    b = r2[1:] # (b) side of the triangle formed by two points and the origin
    c = np.hypot(dx, dy) # (c) side of the triangle formed by two points and the origin

    p = (a + b + c) / 2

    area_term = p * (p - a) * (p - b) * (p - c)
    area_term[area_term < 0] = 0.0
    areas = np.sqrt(area_term)  # Erone di Alessandria
    PortArea = np.sum(areas)

    perimeter = np.sum(c)
    if step == 0.0:
        BurningArea = perimeter * lc
    else:
        #Kerr = 0.2*0.1*2*np.pi/(0.96*16) # from observations
        #rend = 1 - Kerr * perimeter / step
        #Kerr = 0.2 * 0.1 / (2 * np.sqrt(2)) # from observations
        #rend = 1 - 0.908 * Kerr * np.max(r) / step
        #print(rend)

        h = min(np.min(c), step) / 10

        dtheta = h * 360 / step
        n_step = lc / h

        thetas = np.atan2(y, x) + np.deg2rad(dtheta)
        xT = r * np.cos(thetas)
        yT = r * np.sin(thetas)
        s = np.abs(dx*yT - dy*xT + dy*x - dx*y) / np.hypot(dx, dy)

        H = np.hypot(h, s)

        BurningArea = n_step * np.sum(H * c)

    return PortArea, BurningArea

if __name__ == "__main__":
    lc = 2  # lunghezza del grano [m]
    step = 0.1  # passo elica [m]
    n_points_per_side = 50

    # ---- Test 1: quadrato semplice ----
    # definisco quadrato non centrato e punti in ordine casuale
    x_sq = np.array([8.0, 8.0, 0.0, 0.0])
    y_sq = np.array([0.0, 8.0, 8.0, 0.0])
    # mischio gli indici per simulare input disordinato
    perm = np.random.permutation(len(x_sq))
    x_sq_shuffled = x_sq[perm]
    y_sq_shuffled = y_sq[perm]

    print("==== TEST 1: Quadrato (lato=2) ====")

    # trasla e ordina
    x_t, y_t = translate_figure(x_sq_shuffled, y_sq_shuffled)
    x_s, y_s = sort_input(x_t, y_t)


    x_f, y_f = fill_borders(x_s, y_s, n_points_per_side)

    # calcolo superfici
    port_area, burning_area = calculate_surfaces_from_points(x_f, y_f, lc)
    print(f"Quadrato: PortArea = {port_area:.6f} m^2 ; BurningArea (step=0) = {burning_area:.6f} m^2")
    # atteso: PortArea ~ 4 (area quadrato lato 2), ma nota: funzione somma aree triangoli con origine -> area effettiva interna
    # per quadrato centrato l'area dovrebbe essere 4.0

    port_area4, burning_area4 = calculate_surfaces_from_points(x_f, y_f, lc, step)
    print(f"Quadrato: PortArea = {port_area4:.6f} m^2 ; BurningArea (step={step:.3f}) = {burning_area4:.6f} m^2")

    # ---- Test 2: poligono irregolare (approssimazione cerchio) ----
    theta = np.linspace(0, 2 * np.pi, 50, endpoint=False)
    r = 1.0 + 0.2 * np.cos(3 * theta)  # forma non convessa ma chiusa
    x_poly = (r * np.cos(theta)) + 0.5  # traslato per test translate
    y_poly = (r * np.sin(theta)) - 0.3

    print("\n==== TEST 2: Poligono irregolare ====")


    x_t2, y_t2 = translate_figure(x_poly, y_poly)
    x_s2, y_s2 = sort_input(x_t2, y_t2)

    port_area2, burning_area2 = calculate_surfaces_from_points(x_s2, y_s2, lc)
    print(f"Poligono: PortArea = {port_area2:.6f} m^2 ; BurningArea (step=0) = {burning_area2:.6f} m^2")

    # ---- Test 3: burning area with step > 0 (esempio) ----

    port_area3, burning_area3 = calculate_surfaces_from_points(x_s2, y_s2, lc, step)
    print(f"Poligono (step={step} m): PortArea = {port_area3:.6f} m^2 ; BurningArea (step={step:.3f}) = {burning_area3:.6f} m^2")

    # ---- Quick numeric checks: confronto area con shoelace ----
    def shoelace_area(x, y):
        x = np.asarray(x);
        y = np.asarray(y)
        x2 = np.r_[x, x[0]]
        y2 = np.r_[y, y[0]]
        return 0.5 * np.abs(np.sum(x2[:-1] * y2[1:] - x2[1:] * y2[:-1]))


    area_shoelace_sq = shoelace_area(x_s, y_s)
    area_shoelace_poly = shoelace_area(x_s2, y_s2)
    print("\nConfronti con shoelace:")
    print(f"Quadrato: PortArea (triangles) = {port_area:.6f}, Shoelace = {area_shoelace_sq:.6f}")
    print(f"Poligono: PortArea (triangles) = {port_area2:.6f}, Shoelace = {area_shoelace_poly:.6f}")

    """
    plot_polygon(x_sq_shuffled, y_sq_shuffled, title='Quadrato (shuffled input)')
    plot_polygon(x_s, y_s, title='Quadrato (translated + sorted CCW)')
    plot_polygon(x_f, y_f, title='Quadrato (filled borders)')
    plot_polygon(x_poly, y_poly, title='Poligono irregolare (input)')
    plot_polygon(x_s2, y_s2, title='Poligono irregolare (translated + sorted CCW)')
    """

    # Assert ragionevoli (tolleranza)
    tol = 1e-6
    assert abs(port_area - area_shoelace_sq) < 1e-8 or abs(port_area - area_shoelace_sq) / max(area_shoelace_sq,
                                                                                               1e-12) < 1e-6, "PortArea mismatch for square"
    assert abs(port_area2 - area_shoelace_poly) < 1e-6 or abs(port_area2 - area_shoelace_poly) / max(area_shoelace_poly,
                                                                                                     1e-12) < 1e-6, "PortArea mismatch for polygon"

    print("\nTutti i test completati con successo.")


