"""
This script provides the functions to calculate the geometry of a fuel grain and the needed outputs:
    Port area, Burning area, Chamber volume
"""
from xmlrpc.client import Boolean

import numpy as np
import matplotlib.pyplot as plt
from numpy.random import normal


def plot_polygon(x, y, title=None):
    """
    Plots a polygon. Generated by Copilot.
    :param x:
    :param y:
    :param title:
    :return:
    """
    x = np.asarray(x);
    y = np.asarray(y)
    plt.figure(figsize=(5, 5))
    plt.plot(np.r_[x, x[0]], np.r_[y, y[0]], '-o')
    plt.axhline(0, color='k', linewidth=0.5)
    plt.axvline(0, color='k', linewidth=0.5)
    plt.gca().set_aspect('equal', 'box')
    if title:
        plt.title(title)
    plt.show()


def is_between(value, a, b):
    """
    Support function for checking if a value is between a and b
    :param value: value to check
    :param a: first side
    :param b: second side
    :return: Boolean
    """
    start = min([a, b])
    end = max([a, b])

    result = (value >= start and value <= end)
    return result


def create_regular_poligon(n_sides, circum_radius):
    """
    Generates a regular poligon inscripted in the circumference.
    :param n_sides: Number of sides
    :param circum_radius: Radius of circumscribed circonference
    :return: x_poly, y_poly
    """
    theta = 2 * np.pi / n_sides
    thetas = np.arange(0, n_sides, 1)
    thetas = thetas * theta
    x_poly = circum_radius * np.cos(thetas)
    y_poly = circum_radius * np.sin(thetas)
    return x_poly, y_poly


def create_repeated_instance(x, y, n_instances):
    """
    Given the points, repeats an instance around the origin for the given number.
    It also removes the points sharing the same location.
    :param x: x-axis points
    :param y: y-axis points
    :param n_instances: number of instances to repeat
    :return: x_u, y_u
    """
    theta = 2 * np.pi / n_instances
    thetas = np.arange(0, n_instances, 1) * theta

    angles = np.arctan2(y, x)
    radius = np.hypot(x, y)

    angles_rep = []
    radius_rep = []
    for i in range(n_instances):
        angles_rep.append(thetas[i] + angles)
        radius_rep.append(radius)

    angles_rep = np.array(angles_rep).ravel()
    radius_rep = np.array(radius_rep).ravel()

    x_rep = radius_rep * np.cos(angles_rep)
    y_rep = radius_rep * np.sin(angles_rep)

    pts = np.vstack((x_rep, y_rep)).T
    _, idx = np.unique(pts, axis=0, return_index=True)
    idx_sorted = np.sort(idx)
    pts_unique_in_order = pts[idx_sorted]
    x_u, y_u = pts_unique_in_order[:, 0], pts_unique_in_order[:, 1]

    return x_u, y_u


def translate_figure(x, y):
    """
    This function is used to translate the figure coordinates to have the origin inside it.
    :param x: np.array of x values
    :param y: np.array of y values
    :return: x_translated, y_translated
    """
    xG = np.sum(x) / np.size(x)
    yG = np.sum(y) / np.size(y)

    x_translated = x - xG
    y_translated = y - yG
    return x_translated, y_translated


def sort_input(x, y, z=1):
    """
    This function sorts the (x, y) inputs to be couterclock-wise or clock-wise depending on z.
    Use it carefully because it may change the desired geometry.
    :param x: np.array of x values
    :param y: np.array of y values
    :param z: z=1 counterclock, z=-1 clockwise
    :return: x_sorted, y_sorted
    """
    thetas = np.atan2(y, x)
    thetas[thetas < 0] += 2 * np.pi

    thetas = thetas * z
    sorted_indices = np.argsort(thetas)
    x_sorted = x[sorted_indices]
    y_sorted = y[sorted_indices]
    return x_sorted, y_sorted


def fill_borders(x, y, n_points_per_side):
    """
    Linear fill between (x, y) points.
    :param x: x-axis points
    :param y: y-axis points
    :param n_points_per_side: number of points between every x and y
    :return: x_fill, y_fill
    """
    x2 = np.r_[x, x[0]]
    y2 = np.r_[y, y[0]]

    x1 = x2[1:]
    y1 = y2[1:]

    t = np.linspace(0, 1, n_points_per_side + 1)[:-1]
    dx = (x1 - x)[:, None]  # (N,1)
    dy = (y1 - y)[:, None]  # (N,1)
    xs = x[:, None] + dx * t[None, :]  # (N,k)
    ys = y[:, None] + dy * t[None, :]  # (N,k)

    x_fill = xs.ravel()
    y_fill = ys.ravel()

    return x_fill, y_fill


def fill_borders_circumference(x, y, n_points_per_side, tol = 1e-6):
    """
    Circular fill between (x, y) points if they have the same radius, or linear fill otherwise.
    :param x: x-axis points
    :param y: y-axis points
    :param n_points_per_side: number of points between every x and y
    :return: x_fill, y_fill
    """
    if np.asarray(x).size > 1:
        x2 = np.r_[x, x[0]]
        y2 = np.r_[y, y[0]]

        x0 = x2[:-1]
        y0 = y2[:-1]
        x1 = x2[1:]
        y1 = y2[1:]

        t = np.linspace(0, 1, n_points_per_side + 1)[:-1]
        dx = (x1 - x)[:, None]  # (N,1)
        dy = (y1 - y)[:, None]  # (N,1)

        r0 = np.hypot(x0, y0)
        r1 = np.hypot(x1, y1)
        same_r = np.isclose(r0, r1, atol=tol)

        theta0 = np.arctan2(y0, x0)  # (-pi, pi]
        theta1 = np.arctan2(y1, x1)
        delta = theta1 - theta0
        delta = (delta + np.pi) % (2.0 * np.pi) - np.pi

        t_row = t[None, :]  # (1,k)

        xs_lin = x0[:, None] + dx * t_row
        ys_lin = y0[:, None] + dy * t_row

        r0_col = r0[:, None]
        theta0_col = theta0[:, None]
        delta_col = delta[:, None]
        thetas = theta0_col + delta_col * t_row  # (N,k)
        xs_circ = r0_col * np.cos(thetas)
        ys_circ = r0_col * np.sin(thetas)

        mask = same_r[:, None]  # (N,1) broadcastable
        xs_block = np.where(mask, xs_circ, xs_lin)
        ys_block = np.where(mask, ys_circ, ys_lin)

        x_fill = xs_block.ravel()
        y_fill = ys_block.ravel()
    else:
        r = np.hypot(x, y)
        thetas = t = np.linspace(0, 1, n_points_per_side + 1)[:-1] * 2 * np.pi
        x_fill = r * np.cos(thetas)
        y_fill = r * np.sin(thetas)

    return x_fill, y_fill


def calculate_surfaces_from_points(x, y, lc, step=0.0):
    """
    This function calculates port area and burning area of a fuel grain, given the section points and the length.
    If step is different from zero, it calculates the burning area of a swirled grain.
    Burning area calculation has some uncertainties, an efficiency based on observations was developed.
    :param x: np.array of x values [m]
    :param y: np.array of y values [m]
    :param lc: Grain length [m]
    :param step: Helix step [m]
    :return: Port_area [m^2], Burning_area [m^2]
    """

    r = np.hypot(x, y)

    x2 = np.r_[x, x[0]]
    y2 = np.r_[y, y[0]]
    r2 = np.r_[r, r[0]]

    dx = np.diff(x2)
    dy = np.diff(y2)

    a = r2[:-1]  # (a) side of the triangle formed by two points and the origin
    b = r2[1:]  # (b) side of the triangle formed by two points and the origin
    c = np.hypot(dx, dy)  # (c) side of the triangle formed by two points and the origin

    p = (a + b + c) / 2

    area_term = p * (p - a) * (p - b) * (p - c)
    area_term[area_term < 0] = 0.0
    areas = np.sqrt(area_term)  # Erone di Alessandria
    PortArea = np.sum(areas)

    perimeter = np.sum(c)
    if step == 0.0:
        BurningArea = perimeter * lc
    else:
        # Kerr = 0.2*0.1*2*np.pi/(0.96*16) # from observations
        # rend = 1 - Kerr * perimeter / step
        # Kerr = 0.2 * 0.1 / (2 * np.sqrt(2)) # from observations
        # rend = 1 - 0.908 * Kerr * np.max(r) / step
        # print(rend)

        h = min(np.min(c), step) / 10

        dtheta = h * 360 / step
        n_step = lc / h

        thetas = np.atan2(y, x) + np.deg2rad(dtheta)
        xT = r * np.cos(thetas)
        yT = r * np.sin(thetas)
        s = np.abs(dx * yT - dy * xT + dy * x - dx * y) / np.hypot(dx, dy)

        H = np.hypot(h, s)

        BurningArea = n_step * np.sum(H * c)

    return PortArea, BurningArea


# ---------- helper ----------
def remove_close_vertices(x, y, tol=1e-12):
    pts = np.column_stack((np.asarray(x, float), np.asarray(y, float)))
    if pts.shape[0] == 0:
        return np.array([]), np.array([])
    keep = [0]
    for i in range(1, pts.shape[0]):
        if np.hypot(*(pts[i] - pts[keep[-1]])) > tol:
            keep.append(i)
    pts2 = pts[keep]
    return pts2[:,0], pts2[:,1]

def remove_collinear_simple(x, y, tol=1e-12):
    """
    Rimuove punti collineari consecutivi (semplice passaggio).
    Mantiene ordine e chiusura logica.
    """
    x = np.asarray(x, dtype=float).ravel()
    y = np.asarray(y, dtype=float).ravel()
    if x.size < 3:
        return x.copy(), y.copy()
    # ensure closed indexing for checks
    N = x.size
    keep = []
    for i in range(N):
        im = (i-1) % N
        ip = (i+1) % N
        ux, uy = x[i] - x[im], y[i] - y[im]
        vx, vy = x[ip] - x[i], y[ip] - y[i]
        # cross product
        cross = ux * vy - uy * vx
        if abs(cross) > tol:
            keep.append(i)
    if len(keep) < 3:
        # fallback: return original if too aggressive
        return x, y
    x_new = x[keep]; y_new = y[keep]
    return x_new, y_new

def remove_samearc_simple(x, y, tol=1e-12):
    """
    Rimuove punti sullo stesso arco consecutivi (semplice passaggio).
    Mantiene ordine e chiusura logica.
    """
    x = np.asarray(x, dtype=float).ravel()
    y = np.asarray(y, dtype=float).ravel()
    if x.size < 3:
        return x.copy(), y.copy()
    # ensure closed indexing for checks
    N = x.size
    keep = []
    for i in range(N):
        im = (i-1) % N
        ip = (i+1) % N
        rm = np.hypot(x[im], y[im])
        r = np.hypot(x[i], y[i])
        rp = np.hypot(x[ip], y[ip])
        # cross product

        if not(np.isclose(r, rm, atol=tol) & np.isclose(r, rp, atol=tol)):
            keep.append(i)

    x_new = x[keep]; y_new = y[keep]
    if x_new.size < 3:
        try:
            x_new, y_new = x[0], y[0]
        except:
            x_new, y_new = x, y

    return x_new, y_new

def _line_intersection_from_dirs(pA, vA, pB, vB, eps=1e-12):
    """
    Solve pA + s*vA = pB + t*vB for s,t.
    Returns (ok, point, s, t, cond) where ok is True if solution accepted.
    """
    A = np.column_stack((vA, vB))   # 2x2
    b = pB - pA
    det = np.linalg.det(A)
    cond = np.linalg.cond(A) if np.isfinite(det) else np.inf
    if abs(det) < eps or cond > 1e12:
        # try least squares
        try:
            sol, *_ = np.linalg.lstsq(A, b, rcond=None)
            s, t = float(sol[0]), float(sol[1])
            pt = pA + s * vA
            return True, pt, s, t, cond
        except Exception:
            return False, None, None, None, cond
    else:
        sol = np.linalg.solve(A, b)
        s, t = float(sol[0]), float(sol[1])
        pt = pA + s * vA
        return True, pt, s, t, cond

# ---------- main: burn_surface_v4 ----------
def burn_surface_v4(x, y, z, regression_rate, dt,
                    min_param=1e-9, parallel_dot_thresh=0.9999,
                    close_tol=1e-12, merge_tol=1e-9):
    """
    Trasla i midpoint dei lati e trova le intersezioni tramite le tangenti.
    - x,y: contorno (1D arrays, ordine poligono)
    - z: +1/-1 per orientazione normale (normale = rotate tangente by +90 * z)
    - regression_rate, dt -> d = regression_rate * dt
    Returns: x_new, y_new
    info contains diagnostics: conds, fallbacks, midpoints, moved_midpoints
    """
    info = {}
    x = np.asarray(x, dtype=float).ravel()
    y = np.asarray(y, dtype=float).ravel()
    if x.size < 3:
        return np.array([]), np.array([])

    # 0) cleanup duplicates
    x, y = remove_close_vertices(x, y, tol=close_tol)
    x, y = remove_collinear_simple(x, y, tol=close_tol)
    if x.size < 3:
        return np.array([]), np.array([])

    # 1) compute edges and midpoints
    x2 = np.r_[x, x[0]]; y2 = np.r_[y, y[0]]
    dx = np.diff(x2); dy = np.diff(y2)
    edge_len = np.hypot(dx, dy)
    # protect division
    edge_len_safe = edge_len.copy()
    edge_len_safe[edge_len_safe == 0] = 1.0

    # tangents unitari (da vertice i a i+1)
    tx = dx / edge_len_safe
    ty = dy / edge_len_safe
    tang = np.column_stack((tx, ty))

    # midpoints dei lati
    xM = 0.5 * (x2[:-1] + x2[1:])
    yM = 0.5 * (y2[:-1] + y2[1:])

    # --- assicurati che z sia per-edge ---
    z = np.asarray(z).ravel()
    if z.size == 1:
        z = np.ones(xM.shape[0], dtype=float) * z[0]
    elif z.size != xM.shape[0]:
        # se z è per-vertice, converti a per-edge (es. take z at edge start)
        if z.size == x.size:
            z = z  # se vuoi usare per-vertex, mappa opportunamente
        else:
            z = np.resize(z, xM.shape[0])

    # normals (rotate tangenti +90 deg) e applica z
    normals = np.column_stack((ty * z, -tx * z))
    # normalizza normals per sicurezza e gestisci edge quasi nulli
    n_norm = np.hypot(normals[:, 0], normals[:, 1])
    small_edge_mask = (edge_len < 1e-12)
    n_norm[n_norm == 0] = 1.0
    normals[:, 0] /= n_norm
    normals[:, 1] /= n_norm

    # forza direzione verso l'esterno usando il centroide
    """
    cx = np.mean(x)
    cy = np.mean(y)
    centroid = np.array([cx, cy])
    for i_edge in range(normals.shape[0]):
        mid = np.array([xM[i_edge], yM[i_edge]])
        if np.dot(mid - centroid, normals[i_edge]) < 0:
            normals[i_edge] *= -1.0
    """

    # 2) move midpoints along normals con clamp locale
    d = float(regression_rate) * float(dt)
    # clamp factor: frazione della lunghezza minima degli spigoli adiacenti
    clamp_factor = 0.4
    xM_moved = np.empty_like(xM)
    yM_moved = np.empty_like(yM)
    xM_moved = xM + d * normals[:, 0]
    yM_moved = yM + d * normals[:, 1]
    """
    for i_edge in range(xM.size):
        # calcola una d locale basata sulla lunghezza dell'edge
        local_len = edge_len[i_edge] if edge_len[i_edge] > 0 else 1.0
        d_local = min(d, clamp_factor * local_len)
 
        # se edge troppo corto, evita spostamento e segnala
        if small_edge_mask[i_edge]:
            xM_moved[i_edge] = xM[i_edge]
            yM_moved[i_edge] = yM[i_edge]
        else:
            xM_moved[i_edge] = xM[i_edge] + d_local * normals[i_edge, 0]
            yM_moved[i_edge] = yM[i_edge] + d_local * normals[i_edge, 1]
    """
    n = xM_moved.size
    x_new_list = []
    y_new_list = []

    conds = np.zeros(n, dtype=float)
    used_fallback = np.zeros(n, dtype=bool)
    s_vals = np.zeros(n, dtype=float)
    t_vals = np.zeros(n, dtype=float)

    # 3) for each adjacent pair compute intersection of lines along tangents
    # Parametri aggiuntivi locali (regolabili)
    # --- Nuovo ciclo di intersezione con controllo cuspidi e fallback su lati "prima" e "dopo" ---
    miter_factor = 4.0
    max_ray_factor = 10.0
    clamp_factor = 0.4

    x_new_list = []
    y_new_list = []
    conds = np.zeros(n, dtype=float)
    used_fallback = np.zeros(n, dtype=bool)
    s_vals = np.zeros(n, dtype=float)
    t_vals = np.zeros(n, dtype=float)

    for i in range(n):
        ip1 = (i + 1) % n

        # punti e direzioni per i lati i e ip1 (moved midpoints)
        pA = np.array([xM_moved[i], yM_moved[i]])
        vA = tang[i]
        pB = np.array([xM_moved[ip1], yM_moved[ip1]])
        vB = tang[ip1]

        # calcola angolo interno tra i due spigoli (usiamo -vA rispetto a vB)
        # u = -tang[i] (verso il vertice comune), v = tang[ip1] (dal vertice in avanti)
        u = -tang[i]
        v = tang[ip1]
        cosang = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v) + 1e-15)
        cosang = np.clip(cosang, -1.0, 1.0)
        theta = np.arccos(cosang)  # angolo interno al vertice
        theta_half = theta * 0.5

        # calcola d_local per i e ip1 (clamp rispetto alle lunghezze locali)
        lenA = edge_len[i] if edge_len[i] > 0 else 1.0
        lenB = edge_len[ip1] if edge_len[ip1] > 0 else 1.0
        """
        d_local_A = min(d, clamp_factor * lenA)
        d_local_B = min(d, clamp_factor * lenB)
        # usa il valore più conservativo per la soglia
        d_local = min(d_local_A, d_local_B)
        """

        # se theta_half è molto piccolo, tan può esplodere; proteggi
        if theta_half < 1e-8:
            tan_half = 1e8
        else:
            tan_half = np.tan(theta_half)

        cross_product = (normals[i,0] * normals[ip1,1] - normals[i,1] * normals[ip1,0]) * z[i]

        # soglia minima richiesta per i lati adiacenti change with d_local if you want Copilot version
        Lmin = d / (tan_half + 1e-30)

        # se uno dei due lati è troppo corto rispetto alla soglia => cuspide degenerata
        cusp_degenerate = (lenA <= Lmin) or (lenB <= Lmin)

        if cross_product > 0:
            cusp_degenerate = False

        if cusp_degenerate:
            # ignora la traslazione dei due lati i e ip1:
            # effettua l'intersezione tra i lati "prima" e "dopo" quelli considerati:
            if (lenA <= Lmin) & (lenB <= Lmin):
                im = (i - 1) % n
                ip2 = (ip1 + 1) % n
            elif lenA <= Lmin:
                im = (i - 1) % n
                ip2 = ip1
            elif lenB <= Lmin:
                im = i
                ip2 = (ip1 + 1) % n
            # punti e direzioni per i lati di fallback (usiamo moved midpoints se disponibili)
            pA_fb = np.array([xM_moved[im], yM_moved[im]])
            vA_fb = tang[im]
            pB_fb = np.array([xM_moved[ip2], yM_moved[ip2]])
            vB_fb = tang[ip2]

            # se le tangenti di fallback sono quasi parallele, fallback alla media dei moved midpoints
            dot_fb = abs(np.dot(vA_fb, vB_fb) / (np.linalg.norm(vA_fb) * np.linalg.norm(vB_fb) + 1e-15))
            if dot_fb >= parallel_dot_thresh:
                pt = 0.5 * (pA_fb + pB_fb)
                used_fallback[i] = True
                conds[i] = np.inf
                s_vals[i] = np.nan;
                t_vals[i] = np.nan
            else:
                ok_fb, pt_fb, s_fb, t_fb, cond_fb = _line_intersection_from_dirs(pA_fb, vA_fb, pB_fb, vB_fb)
                conds[i] = cond_fb if np.isfinite(cond_fb) else np.inf
                if ok_fb and np.isfinite(s_fb) and np.isfinite(t_fb):
                    # accetta l'intersezione di fallback se ragionevole (non troppo lontana)
                    distA_fb = np.hypot(*(pt_fb - pA_fb))
                    distB_fb = np.hypot(*(pt_fb - pB_fb))
                    max_miter_fb = miter_factor * min(edge_len[im], edge_len[ip2])
                    if (distA_fb <= max_miter_fb and distB_fb <= max_miter_fb) or (s_fb >= 0 and t_fb >= 0):
                        pt = pt_fb
                        used_fallback[i] = False
                        s_vals[i] = s_fb;
                        t_vals[i] = t_fb
                    else:
                        pt = 0.5 * (pA_fb + pB_fb)
                        used_fallback[i] = True
                        s_vals[i] = s_fb;
                        t_vals[i] = t_fb
                else:
                    pt = 0.5 * (pA_fb + pB_fb)
                    used_fallback[i] = True
                    s_vals[i] = s_fb if 's_fb' in locals() else np.nan
                    t_vals[i] = t_fb if 't_fb' in locals() else np.nan

            x_new_list.append(pt[0]);
            y_new_list.append(pt[1])
            # continua al prossimo i
            continue

        # --- caso normale: intersezione tra le tangenti dei moved midpoints i e ip1 ---
        # fallback immediato se tangenti quasi parallele
        dot = abs(np.dot(vA, vB) / (np.linalg.norm(vA) * np.linalg.norm(vB) + 1e-15))
        if dot >= parallel_dot_thresh:
            pt = 0.5 * (pA + pB)
            x_new_list.append(pt[0]);
            y_new_list.append(pt[1])
            conds[i] = np.inf
            used_fallback[i] = True
            s_vals[i] = np.nan;
            t_vals[i] = np.nan
            continue

        ok, pt, s, t, cond = _line_intersection_from_dirs(pA, vA, pB, vB)
        conds[i] = cond if np.isfinite(cond) else np.inf

        # limiti basati sulle lunghezze degli spigoli adiacenti
        max_miter = miter_factor * min(lenA, lenB)
        max_ray = max_ray_factor * min(lenA, lenB)

        valid = False
        if ok and np.isfinite(s) and np.isfinite(t):
            distA = np.hypot(*(pt - pA))
            distB = np.hypot(*(pt - pB))
            if (s >= min_param and t >= min_param) and (distA <= max_miter and distB <= max_miter):
                valid = True
            else:
                if (s >= 0.0 and t >= 0.0) and (distA <= max_ray and distB <= max_ray):
                    valid = True

        if not valid:
            """
            rAB = 0.5 * (pB - pA)
            rAB_mod = np.hypot(rAB[0], rAB[1])
            tAB_mod = - (rAB_mod**2) / (rAB[0] * abs(vA[0]) - rAB[1] * abs(vA[1]))
            pt = pA + tAB_mod * vA
            """
            """
            pt = 0.5 * (pA + pB)
            r_pt = np.hypot(pt[0], pt[1])
            pt = pt * (1 + 0.5* d / r_pt)
            """
            if cross_product > 1e-12:
                pt = np.array([x[ip1], y[ip1]])
                pt = pt + normals[i, :] * d
                x_new_list.append(pt[0]); y_new_list.append(pt[1])
                pt = np.array([x[ip1], y[ip1]])
                pt = pt + normals[ip1, :] * d
            else:
                pt = 0.5 * (pB + pA)

            used_fallback[i] = True
        else:
            used_fallback[i] = False

        x_new_list.append(pt[0]);
        y_new_list.append(pt[1])
        s_vals[i] = s if s is not None else np.nan
        t_vals[i] = t if t is not None else np.nan

    x_new = np.asarray(x_new_list, dtype=float)
    y_new = np.asarray(y_new_list, dtype=float)

    # 4) cleanup: remove near-duplicates and simple collinearities
    x_new, y_new = remove_close_vertices(x_new, y_new, tol=close_tol)
    x_new, y_new = remove_collinear_simple(x_new, y_new, tol=close_tol)

    # 5) final safety: if result self-intersects badly, fallback to conservative midpoint shrink
    def _has_self_intersection_local(xx, yy):
        m = xx.size
        if m < 4:
            return False
        pts = np.column_stack((xx, yy))
        for a in range(m):
            A = pts[a]; B = pts[(a+1)%m]
            for b in range(a+2, m):
                if (b+1)%m == a:
                    continue
                C = pts[b]; D = pts[(b+1)%m]
                # simple segment intersection test
                def orient(ax,ay,bx,by,cx,cy):
                    return (bx-ax)*(cy-ay) - (by-ay)*(cx-ax)
                o1 = orient(A[0],A[1],B[0],B[1],C[0],C[1])
                o2 = orient(A[0],A[1],B[0],B[1],D[0],D[1])
                o3 = orient(C[0],C[1],D[0],D[1],A[0],A[1])
                o4 = orient(C[0],C[1],D[0],D[1],B[0],B[1])
                if o1*o2 < 0 and o3*o4 < 0:
                    return True
        return False

    if _has_self_intersection_local(x_new, y_new):
        # conservative fallback: shrink midpoints toward polygon centroid by factor 0.5 and recompute intersections
        cx = np.mean(x); cy = np.mean(y)
        xM_shrunk = 0.5*(xM + np.array([cx]*n))
        yM_shrunk = 0.5*(yM + np.array([cy]*n))
        xM_moved = xM_shrunk + d * normals[:,0]
        yM_moved = yM_shrunk + d * normals[:,1]
        x_new_list = []; y_new_list = []
        for i in range(n):
            ip1 = (i + 1) % n
            pA = np.array([xM_moved[i], yM_moved[i]])
            vA = tang[i]
            pB = np.array([xM_moved[ip1], yM_moved[ip1]])
            vB = tang[ip1]
            ok, pt, s, t, cond = _line_intersection_from_dirs(pA, vA, pB, vB)
            if not ok:
                pt = 0.5*(pA + pB)
            x_new_list.append(pt[0]); y_new_list.append(pt[1])
        x_new = np.asarray(x_new_list); y_new = np.asarray(y_new_list)
        x_new, y_new = remove_close_vertices(x_new, y_new, tol=close_tol)
        x_new, y_new = remove_collinear_simple(x_new, y_new, tol=close_tol)

    # diagnostics
    info["midpoints"] = np.column_stack((xM, yM))
    info["moved_midpoints"] = np.column_stack((xM_moved, yM_moved))
    info["tangents"] = tang
    info["conds"] = conds
    info["used_fallback"] = used_fallback
    info["s_vals"] = s_vals
    info["t_vals"] = t_vals

    return x_new, y_new, xM_moved, yM_moved


def burn_surface_circular(x, y, z, regression_rate, dt,
                    min_param=1e-9, parallel_dot_thresh=0.9999,
                    close_tol=1e-12, merge_tol=1e-9):
    """
    Trasla i midpoint dei lati e trova le intersezioni tramite le tangenti.
    - x,y: contorno (1D arrays, ordine poligono)
    - z: +1/-1 per orientazione normale (normale = rotate tangente by +90 * z)
    - regression_rate, dt -> d = regression_rate * dt
    Returns: x_new, y_new
    info contains diagnostics: conds, fallbacks, midpoints, moved_midpoints
    """
    info = {}
    x = np.asarray(x, dtype=float).ravel()
    y = np.asarray(y, dtype=float).ravel()

    # 0) cleanup duplicates
    x, y = remove_close_vertices(x, y, tol=close_tol)
    x, y = remove_collinear_simple(x, y, tol=close_tol)
    x, y = remove_samearc_simple(x, y, tol=close_tol)

    if x.size > 2:
        # 1) compute edges and midpoints
        x2 = np.r_[x, x[0]];
        y2 = np.r_[y, y[0]]

        rads = np.hypot(x, y)
        rads2 = np.hypot(x2, y2)

        dx = np.diff(x2);
        dy = np.diff(y2)
        edge_len = np.hypot(dx, dy)
        # protect division
        edge_len_safe = edge_len.copy()
        edge_len_safe[edge_len_safe == 0] = 1.0

        # tangents unitari (da vertice i a i+1)
        tx = dx / edge_len_safe
        ty = dy / edge_len_safe
        tang = np.column_stack((tx, ty))

        mask_same_rad = np.zeros_like(x, dtype=bool)
        for i in range(x.size):
            if np.isclose(rads2[i], rads2[i+1], atol=close_tol):
                mask_same_rad[i] = True

        # midpoints dei lati
        xM = 0.5 * (x2[:-1] + x2[1:])
        yM = 0.5 * (y2[:-1] + y2[1:])

        # --- assicurati che z sia per-edge ---
        z = np.asarray(z).ravel()
        if z.size == 1:
            z = np.ones(xM.shape[0], dtype=float) * z[0]
        elif z.size != xM.shape[0]:
            # se z è per-vertice, converti a per-edge (es. take z at edge start)
            if z.size == x.size:
                z = z  # se vuoi usare per-vertex, mappa opportunamente
            else:
                z = np.resize(z, xM.shape[0])

        # normals (rotate tangenti +90 deg) e applica z
        normals = np.column_stack((ty * z, -tx * z))
        # normalizza normals per sicurezza e gestisci edge quasi nulli
        n_norm = np.hypot(normals[:, 0], normals[:, 1])
        small_edge_mask = (edge_len < 1e-12)
        n_norm[n_norm == 0] = 1.0
        normals[:, 0] /= n_norm
        normals[:, 1] /= n_norm

    else:
        try:
            xM = x[0]
            yM = y[0]
        except IndexError:
            xM = x
            yM = y

        mask_same_rad = np.ones_like(xM, dtype=bool)
        normals = np.array([(xM / np.hypot(xM, yM)), (yM / np.hypot(xM, yM))])
        tang = np.array([(- yM * z / np.hypot(xM, yM)), (xM * z / np.hypot(xM, yM))])

    # forza direzione verso l'esterno usando il centroide
    """
    cx = np.mean(x)
    cy = np.mean(y)
    centroid = np.array([cx, cy])
    for i_edge in range(normals.shape[0]):
        mid = np.array([xM[i_edge], yM[i_edge]])
        if np.dot(mid - centroid, normals[i_edge]) < 0:
            normals[i_edge] *= -1.0
    """

    # 2) move midpoints along normals con clamp locale
    d = float(regression_rate) * float(dt)
    # clamp factor: frazione della lunghezza minima degli spigoli adiacenti
    clamp_factor = 0.4
    xM_moved = np.empty_like(xM)
    yM_moved = np.empty_like(yM)
    try:
        xM_moved = xM + d * normals[:, 0]
        yM_moved = yM + d * normals[:, 1]
    except:
        xM_moved = xM + d * normals[0]
        yM_moved = yM + d * normals[1]
    """
    for i_edge in range(xM.size):
        # calcola una d locale basata sulla lunghezza dell'edge
        local_len = edge_len[i_edge] if edge_len[i_edge] > 0 else 1.0
        d_local = min(d, clamp_factor * local_len)

        # se edge troppo corto, evita spostamento e segnala
        if small_edge_mask[i_edge]:
            xM_moved[i_edge] = xM[i_edge]
            yM_moved[i_edge] = yM[i_edge]
        else:
            xM_moved[i_edge] = xM[i_edge] + d_local * normals[i_edge, 0]
            yM_moved[i_edge] = yM[i_edge] + d_local * normals[i_edge, 1]
    """
    n = np.asarray(xM_moved).size
    x_new_list = []
    y_new_list = []

    conds = np.zeros(n, dtype=float)
    used_fallback = np.zeros(n, dtype=bool)
    s_vals = np.zeros(n, dtype=float)
    t_vals = np.zeros(n, dtype=float)

    # 3) for each adjacent pair compute intersection of lines along tangents
    # Parametri aggiuntivi locali (regolabili)
    # --- Nuovo ciclo di intersezione con controllo cuspidi e fallback su lati "prima" e "dopo" ---
    miter_factor = 4.0
    max_ray_factor = 10.0
    clamp_factor = 0.4

    x_new_list = []
    y_new_list = []
    conds = np.zeros(n, dtype=float)
    used_fallback = np.zeros(n, dtype=bool)
    s_vals = np.zeros(n, dtype=float)
    t_vals = np.zeros(n, dtype=float)

    for i in range(n):

        if n > 2:
            ip1 = (i + 1) % n
        else:
            x_new_list.append(xM_moved);
            y_new_list.append(yM_moved)
            continue

        # punti e direzioni per i lati i e ip1 (moved midpoints)
        pA = np.array([xM_moved[i], yM_moved[i]])
        vA = tang[i]
        pB = np.array([xM_moved[ip1], yM_moved[ip1]])
        vB = tang[ip1]

        # calcola angolo interno tra i due spigoli (usiamo -vA rispetto a vB)
        # u = -tang[i] (verso il vertice comune), v = tang[ip1] (dal vertice in avanti)
        u = -tang[i]
        v = tang[ip1]
        cosang = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v) + 1e-15)
        cosang = np.clip(cosang, -1.0, 1.0)
        theta = np.arccos(cosang)  # angolo interno al vertice
        theta_half = theta * 0.5

        # calcola d_local per i e ip1 (clamp rispetto alle lunghezze locali)
        lenA = edge_len[i] if edge_len[i] > 0 else 1.0
        lenB = edge_len[ip1] if edge_len[ip1] > 0 else 1.0
        """
        d_local_A = min(d, clamp_factor * lenA)
        d_local_B = min(d, clamp_factor * lenB)
        # usa il valore più conservativo per la soglia
        d_local = min(d_local_A, d_local_B)
        """

        # se theta_half è molto piccolo, tan può esplodere; proteggi
        if theta_half < 1e-8:
            tan_half = 1e8
        else:
            tan_half = np.tan(theta_half)

        cross_product = (normals[i, 0] * normals[ip1, 1] - normals[i, 1] * normals[ip1, 0]) * z[i]

        # soglia minima richiesta per i lati adiacenti change with d_local if you want Copilot version
        Lmin = d / (tan_half + 1e-30)

        # se uno dei due lati è troppo corto rispetto alla soglia => cuspide degenerata
        cusp_degenerate = (lenA <= Lmin) or (lenB <= Lmin)

        if cross_product > 0:
            cusp_degenerate = False

        if cusp_degenerate:
            print('Degenerate cusp')
            # ignora la traslazione dei due lati i e ip1:
            # effettua l'intersezione tra i lati "prima" e "dopo" quelli considerati:
            if (lenA <= Lmin) & (lenB <= Lmin):
                im = (i - 1) % n
                ip2 = (ip1 + 1) % n
            elif lenA <= Lmin:
                im = (i - 1) % n
                ip2 = ip1
            elif lenB <= Lmin:
                im = i
                ip2 = (ip1 + 1) % n

            # punti e direzioni per i lati di fallback (usiamo moved midpoints se disponibili)
            pA_fb = np.array([xM_moved[im], yM_moved[im]])
            vA_fb = tang[im]
            pB_fb = np.array([xM_moved[ip2], yM_moved[ip2]])
            vB_fb = tang[ip2]

            # se le tangenti di fallback sono quasi parallele, fallback alla media dei moved midpoints
            dot_fb = abs(np.dot(vA_fb, vB_fb) / (np.linalg.norm(vA_fb) * np.linalg.norm(vB_fb) + 1e-15))
            if dot_fb >= parallel_dot_thresh:
                pt = 0.5 * (pA_fb + pB_fb)
                used_fallback[i] = True
                conds[i] = np.inf
                s_vals[i] = np.nan;
                t_vals[i] = np.nan
            else:
                ok_fb, pt_fb, s_fb, t_fb, cond_fb = _line_intersection_from_dirs(pA_fb, vA_fb, pB_fb, vB_fb)
                conds[i] = cond_fb if np.isfinite(cond_fb) else np.inf
                if ok_fb and np.isfinite(s_fb) and np.isfinite(t_fb):
                    # accetta l'intersezione di fallback se ragionevole (non troppo lontana)
                    distA_fb = np.hypot(*(pt_fb - pA_fb))
                    distB_fb = np.hypot(*(pt_fb - pB_fb))
                    max_miter_fb = miter_factor * min(edge_len[im], edge_len[ip2])
                    if (distA_fb <= max_miter_fb and distB_fb <= max_miter_fb) or (s_fb >= 0 and t_fb >= 0):
                        pt = pt_fb
                        used_fallback[i] = False
                        s_vals[i] = s_fb;
                        t_vals[i] = t_fb
                    else:
                        pt = 0.5 * (pA_fb + pB_fb)
                        used_fallback[i] = True
                        s_vals[i] = s_fb;
                        t_vals[i] = t_fb
                else:
                    pt = 0.5 * (pA_fb + pB_fb)
                    used_fallback[i] = True
                    s_vals[i] = s_fb if 's_fb' in locals() else np.nan
                    t_vals[i] = t_fb if 't_fb' in locals() else np.nan

            x_new_list.append(pt[0]);
            y_new_list.append(pt[1])
            # continua al prossimo i
            continue

        # --- caso normale: intersezione tra le tangenti dei moved midpoints i e ip1 ---
        # fallback immediato se tangenti quasi parallele
        dot = abs(np.dot(vA, vB) / (np.linalg.norm(vA) * np.linalg.norm(vB) + 1e-15))
        if dot >= parallel_dot_thresh:
            pt = 0.5 * (pA + pB)
            x_new_list.append(pt[0]);
            y_new_list.append(pt[1])
            conds[i] = np.inf
            used_fallback[i] = True
            s_vals[i] = np.nan;
            t_vals[i] = np.nan
            continue

        ok, pt, s, t, cond = _line_intersection_from_dirs(pA, vA, pB, vB)
        conds[i] = cond if np.isfinite(cond) else np.inf

        # limiti basati sulle lunghezze degli spigoli adiacenti
        max_miter = miter_factor * min(lenA, lenB)
        max_ray = max_ray_factor * min(lenA, lenB)

        valid = False
        if ok and np.isfinite(s) and np.isfinite(t):
            distA = np.hypot(*(pt - pA))
            distB = np.hypot(*(pt - pB))
            if (s >= min_param and t >= min_param) and (distA <= max_miter and distB <= max_miter):
                valid = True
            else:
                if (s >= 0.0 and t >= 0.0) and (distA <= max_ray and distB <= max_ray):
                    valid = True

        if not valid:
            """
            rAB = 0.5 * (pB - pA)
            rAB_mod = np.hypot(rAB[0], rAB[1])
            tAB_mod = - (rAB_mod**2) / (rAB[0] * abs(vA[0]) - rAB[1] * abs(vA[1]))
            pt = pA + tAB_mod * vA
            """
            """
            pt = 0.5 * (pA + pB)
            r_pt = np.hypot(pt[0], pt[1])
            pt = pt * (1 + 0.5* d / r_pt)
            """
            if cross_product > 1e-12:
                if mask_same_rad[i]:
                    pt = np.array([x[ip1], y[ip1]])
                    pt = pt + normals[i, :] * d
                elif mask_same_rad[ip1]:
                    pt = np.array([x[ip1], y[ip1]])
                    pt = pt + normals[ip1, :] * d
                else:
                    pt = np.array([x[ip1], y[ip1]])
                    pt = pt + normals[i, :] * d
                    x_new_list.append(pt[0]);
                    y_new_list.append(pt[1])
                    pt = np.array([x[ip1], y[ip1]])
                    pt = pt + normals[ip1, :] * d
            else:
                pt = 0.5 * (pB + pA)

            used_fallback[i] = True
        else:
            used_fallback[i] = False

        x_new_list.append(pt[0]);
        y_new_list.append(pt[1])
        s_vals[i] = s if s is not None else np.nan
        t_vals[i] = t if t is not None else np.nan

    x_new = np.asarray(x_new_list, dtype=float)
    y_new = np.asarray(y_new_list, dtype=float)

    # 4) cleanup: remove near-duplicates and simple collinearities
    x_new, y_new = remove_close_vertices(x_new, y_new, tol=close_tol)
    x_new, y_new = remove_collinear_simple(x_new, y_new, tol=close_tol)

    # 5) final safety: if result self-intersects badly, fallback to conservative midpoint shrink
    def _has_self_intersection_local(xx, yy):
        m = xx.size
        if m < 4:
            return False
        pts = np.column_stack((xx, yy))
        for a in range(m):
            A = pts[a];
            B = pts[(a + 1) % m]
            for b in range(a + 2, m):
                if (b + 1) % m == a:
                    continue
                C = pts[b];
                D = pts[(b + 1) % m]

                # simple segment intersection test
                def orient(ax, ay, bx, by, cx, cy):
                    return (bx - ax) * (cy - ay) - (by - ay) * (cx - ax)

                o1 = orient(A[0], A[1], B[0], B[1], C[0], C[1])
                o2 = orient(A[0], A[1], B[0], B[1], D[0], D[1])
                o3 = orient(C[0], C[1], D[0], D[1], A[0], A[1])
                o4 = orient(C[0], C[1], D[0], D[1], B[0], B[1])
                if o1 * o2 < 0 and o3 * o4 < 0:
                    return True
        return False

    if _has_self_intersection_local(x_new, y_new):
        # conservative fallback: shrink midpoints toward polygon centroid by factor 0.5 and recompute intersections
        cx = np.mean(x);
        cy = np.mean(y)
        xM_shrunk = 0.5 * (xM + np.array([cx] * n))
        yM_shrunk = 0.5 * (yM + np.array([cy] * n))
        xM_moved = xM_shrunk + d * normals[:, 0]
        yM_moved = yM_shrunk + d * normals[:, 1]
        x_new_list = [];
        y_new_list = []
        for i in range(n):
            ip1 = (i + 1) % n
            pA = np.array([xM_moved[i], yM_moved[i]])
            vA = tang[i]
            pB = np.array([xM_moved[ip1], yM_moved[ip1]])
            vB = tang[ip1]
            ok, pt, s, t, cond = _line_intersection_from_dirs(pA, vA, pB, vB)
            if not ok:
                pt = 0.5 * (pA + pB)
            x_new_list.append(pt[0]);
            y_new_list.append(pt[1])
        x_new = np.asarray(x_new_list);
        y_new = np.asarray(y_new_list)
        x_new, y_new = remove_close_vertices(x_new, y_new, tol=close_tol)
        x_new, y_new = remove_collinear_simple(x_new, y_new, tol=close_tol)

    # diagnostics
    info["midpoints"] = np.column_stack((xM, yM))
    info["moved_midpoints"] = np.column_stack((xM_moved, yM_moved))
    info["tangents"] = tang
    info["conds"] = conds
    info["used_fallback"] = used_fallback
    info["s_vals"] = s_vals
    info["t_vals"] = t_vals

    return x_new, y_new, xM_moved[mask_same_rad], yM_moved[mask_same_rad]


if __name__ == "__main__":
    # lc = 2  # lunghezza del grano [m]
    radius = 8
    step = 26.336  # passo elica [m]
    lc = step
    n_points_per_side = 100
    n_sides = 6

    # ---- Test 1: poligono semplice ----
    x_sq, y_sq = create_regular_poligon(n_sides, radius)
    # mischio gli indici per simulare input disordinato
    perm = np.random.permutation(len(x_sq))
    x_sq_shuffled = x_sq[perm]
    y_sq_shuffled = y_sq[perm]

    print(f"==== TEST 1: Poligono (lato={n_sides}) ====")

    # trasla e ordina
    x_t, y_t = translate_figure(x_sq_shuffled, y_sq_shuffled)
    x_s, y_s = sort_input(x_t, y_t)

    x_f, y_f = fill_borders(x_s, y_s, n_points_per_side)

    x_f2, y_f2, xM, yM = burn_surface_v4(x_f, y_f, 1, 0.5, 1)

    for i in range(0):
        x_f2, y_f2, xM, yM = burn_surface_v4(x_f2, y_f2, 1, 0.5, 1)
    
    plt.figure()
    plt.plot(x_f, y_f, 'b')
    plt.plot(x_f2, y_f2, 'r', label='burned')
    plt.plot(xM, yM, 'ko')
    plt.legend()
    plt.show()


    # ---- Test 2: poligono irregolare (approssimazione cerchio) ----
    theta = np.linspace(0, 2 * np.pi, 100, endpoint=False)
    r = 1.0 + 0.2 * np.cos(10 * theta)  # forma non convessa ma chiusa
    x_poly = (r * np.cos(theta))  # traslato per test translate
    y_poly = (r * np.sin(theta))

    print("\n==== TEST 2: Poligono irregolare ====")

    # x_t2, y_t2 = translate_figure(x_poly, y_poly)
    # x_s2, y_s2 = sort_input(x_t2, y_t2)
    x_s2, y_s2 = sort_input(x_poly, y_poly)

    plt.figure()
    plt.plot(x_s2, y_s2, 'b', label='original')

    x_s2b, y_s2b, xM, yM = burn_surface_v4(x_s2, y_s2, 1, 0.05, 1)
    plt.plot(x_s2b, y_s2b, 'r')

    for crazy_times in range(0):
        for times in range(3):
            x_s2b, y_s2b, xM, yM = burn_surface_v4(x_s2b, y_s2b, 1, 0.05, 1)
            plt.plot(x_s2b, y_s2b, ['g', 'y', 'k'][times])

    for times in range(0):
        x_s2b, y_s2b, xM, yM  = burn_surface_v4(x_s2b, y_s2b, 1, 0.05, 1)
        plt.plot(x_s2b, y_s2b, ['g', 'y', 'k'][times])

    plt.plot(xM, yM, 'ko')

    plt.legend()
    plt.show()

    # ============= SVP INDUSTRIES 5 POINTS - Stella a 5 punte =============
    # Parametri stella
    D_int_base = 6.62e-3  # [m] = 6.62 mm
    D_ext = 20.0e-3  # [m] = 20.0 mm

    r_interno = D_int_base / 2  # 3.31 mm
    r_esterno = D_ext / 2  # 10.0 mm

    # Raggio punta arrotondata (95% del raggio esterno per punte meno appuntite)
    r_punta = 0.95 * r_esterno  # 9.5 mm invece di 10.0 mm

    n_points_side = 20  # Più punti per curve più morbide

    # ===== LATO SUPERIORE (da insenatura sinistra a punta) =====
    upper_angles = np.linspace(np.deg2rad(-18), np.deg2rad(0), n_points_side)

    # Transizione CURVA con funzione cubica per lati più arrotondati
    t_upper = np.linspace(0, 1, n_points_side)
    # Funzione cubica per transizione molto morbida e curva
    upper_radii = r_interno + (r_punta - r_interno) * (t_upper ** 2) * (3 - 2 * t_upper)

    upper_points = []
    for angle, radius in zip(upper_angles, upper_radii):
        upper_points.append([radius * np.cos(angle), radius * np.sin(angle)])

    # ===== LATO INFERIORE (da punta a insenatura destra) =====
    lower_angles = np.linspace(np.deg2rad(0), np.deg2rad(18), n_points_side)

    # Transizione CURVA con funzione cubica
    t_lower = np.linspace(0, 1, n_points_side)
    lower_radii = r_punta + (r_interno - r_punta) * (t_lower ** 2) * (3 - 2 * t_lower)

    lower_points = []
    for angle, radius in zip(lower_angles, lower_radii):
        lower_points.append([radius * np.cos(angle), radius * np.sin(angle)])

    # Combino i due lati
    svp_instance = np.array(upper_points + lower_points[1:])

    print(f"SVP INDUSTRIES 5 POINTS - {svp_instance.shape[0]} punti per sezione:")
    print("=" * 70)
    print(f"  Raggio interno (insenature): {r_interno * 1000:.2f} mm")
    print(f"  Raggio punta (arrotondata): {r_punta * 1000:.2f} mm")
    print(f"  Funzione transizione: cubica smoothstep per curve morbide")
    print("=" * 70)

    # Replica 5 volte per creare la stella completa
    svp_points_x, svp_points_y = create_repeated_instance(svp_instance[:, 0], svp_instance[:, 1], 5)
    svp_centered_x, svp_centered_y = translate_figure(svp_points_x, svp_points_y)

    print(f"\nPunti totali dopo replicazione x5: {len(svp_points_x)} punti")

    # Fill con archi circolari
    svp_filled_x, svp_filled_y = fill_borders_circumference(svp_centered_x, svp_centered_y, 40, tol=1e-5)

    print(f"Punti dopo fill_borders_circumference: {len(svp_filled_x)} punti")

    # ============= BURNING PROGRESSIVO VERSO ESTERNO (FINO AL CASING) =============
    plt.figure(figsize=(14, 14))

    # Cerchio casing
    theta_casing = np.linspace(0, 2 * np.pi, 200)
    plt.plot(15.0 * np.cos(theta_casing), 15.0 * np.sin(theta_casing),
             'k-', linewidth=3.5, label='Casing D=30mm', zorder=10)

    # Stella iniziale
    plt.plot(svp_filled_x * 1000, svp_filled_y * 1000, 'b', linewidth=4,
             label='Stella iniziale', zorder=9)

    # Parametri burning - AUMENTATO per raggiungere il casing
    # Distanza: dalla stella (r~9.5mm) al casing (r=15mm) = ~5.5mm
    # Con 8 iterazioni: 5.5/8 = 0.69mm per step
    regression_rate_tocasing = 0.00069  # m/s (0.69 mm/s)
    dt = 1.0  # s
    n_iterations = 8  # 8 iterazioni

    print(f"\n{'=' * 70}")
    print(f"SVP INDUSTRIES 5 POINTS - PARAMETRI BURNING VERSO ESTERNO:")
    print(f"  Regression rate: {regression_rate_tocasing * 1000:.2f} mm/s")
    print(f"  Time step: {dt:.1f} s")
    print(f"  Numero iterazioni: {n_iterations}")
    print(f"  Passo tra linee: {regression_rate_tocasing * dt * 1000:.2f} mm")
    print(f"  Distanza totale coperta: {regression_rate_tocasing * dt * n_iterations * 1000:.2f} mm")
    print(f"  (dovrebbe raggiungere il casing a r=15mm)")
    print(f"{'=' * 70}\n")

    # Burning progressivo VERSO ESTERNO (z=+1)
    svp_burned_x, svp_burned_y, svp_xM, svp_yM = burn_surface_circular(
        svp_centered_x, svp_centered_y, 1, regression_rate_tocasing, dt)  # z=1 per ESTERNO

    svp_refilled_x, svp_refilled_y = fill_borders_circumference(svp_burned_x, svp_burned_y, 40, tol=1e-5)

    colors = plt.cm.rainbow(np.linspace(0, 1, n_iterations))

    # Mostro TUTTE le 8 linee intermedie (SENZA la linea rossa finale)
    for times in range(n_iterations):
        svp_burned_x, svp_burned_y, svp_xM, svp_yM = burn_surface_circular(
            svp_burned_x, svp_burned_y, 1, regression_rate_tocasing, dt)  # z=1 per ESTERNO

        if len(svp_burned_x) < 3:
            print(f"Geometria collassata all'iterazione {times}")
            break

        svp_refilled_x, svp_refilled_y = fill_borders_circumference(svp_burned_x, svp_burned_y, 40, tol=1e-5)

        # Plotto OGNI iterazione
        plt.plot(svp_refilled_x * 1000, svp_refilled_y * 1000,
                 color=colors[times], alpha=0.8, linewidth=2.2, zorder=8 - times * 0.1)

    # NON plotto la linea rossa finale (rimosso plt.plot con 'r')

    plt.axis('equal')
    plt.grid(True, alpha=0.3, linestyle=':', linewidth=0.8)
    plt.legend(fontsize=14, loc='upper right', framealpha=0.98, edgecolor='black', fancybox=True)
    plt.title('SVP Industries 5 Points - Burning Progression\n' +
              f'Espansione verso casing | Passo={regression_rate_tocasing * dt * 1000:.2f}mm | {n_iterations} iterazioni',
              fontsize=16, weight='bold', pad=20)
    plt.xlabel('Posizione X (mm)', fontsize=14, weight='bold')
    plt.ylabel('Posizione Y (mm)', fontsize=14, weight='bold')
    plt.xlim(-17, 17)
    plt.ylim(-17, 17)
    plt.tight_layout()
    plt.show()

    print(f"\n✓ SVP Industries 5 Points - Visualizzazione completata!")
    print(f"  Linee totali mostrate: {n_iterations + 1} linee")
    print(f"  (1 blu iniziale + {n_iterations} colorate intermedie)")
    print(f"  Espansione verso il casing fino a r≈15mm!")

    # ============= SVP INDUSTRIES 5 POINTS - Stella a 5 punte =============
    # Parametri stella
    D_int_base = 6.62e-3  # [m] = 6.62 mm
    D_ext = 20.0e-3  # [m] = 20.0 mm

    r_interno = D_int_base / 2  # 3.31 mm
    r_esterno = D_ext / 2  # 10.0 mm

    # Raggio punta arrotondata (95% del raggio esterno per punte meno appuntite)
    r_punta = 0.95 * r_esterno  # 9.5 mm invece di 10.0 mm

    n_points_side = 20  # Più punti per curve più morbide

    # ===== LATO SUPERIORE (da insenatura sinistra a punta) =====
    upper_angles = np.linspace(np.deg2rad(-18), np.deg2rad(0), n_points_side)

    # Transizione CURVA con funzione cubica per lati più arrotondati
    t_upper = np.linspace(0, 1, n_points_side)
    # Funzione cubica per transizione molto morbida e curva
    upper_radii = r_interno + (r_punta - r_interno) * (t_upper ** 2) * (3 - 2 * t_upper)

    upper_points = []
    for angle, radius in zip(upper_angles, upper_radii):
        upper_points.append([radius * np.cos(angle), radius * np.sin(angle)])

    # ===== LATO INFERIORE (da punta a insenatura destra) =====
    lower_angles = np.linspace(np.deg2rad(0), np.deg2rad(18), n_points_side)

    # Transizione CURVA con funzione cubica
    t_lower = np.linspace(0, 1, n_points_side)
    lower_radii = r_punta + (r_interno - r_punta) * (t_lower ** 2) * (3 - 2 * t_lower)

    lower_points = []
    for angle, radius in zip(lower_angles, lower_radii):
        lower_points.append([radius * np.cos(angle), radius * np.sin(angle)])

    # Combino i due lati
    svp_instance = np.array(upper_points + lower_points[1:])

    print(f"SVP INDUSTRIES 5 POINTS - {svp_instance.shape[0]} punti per sezione:")
    print("=" * 70)
    print(f"  Raggio interno (insenature): {r_interno * 1000:.2f} mm")
    print(f"  Raggio punta (arrotondata): {r_punta * 1000:.2f} mm")
    print("=" * 70)

    # Replica 5 volte per creare la stella completa
    svp_points_x, svp_points_y = create_repeated_instance(svp_instance[:, 0], svp_instance[:, 1], 5)
    svp_centered_x, svp_centered_y = translate_figure(svp_points_x, svp_points_y)

    print(f"\nPunti totali dopo replicazione x5: {len(svp_points_x)} punti")

    # Fill con archi circolari
    svp_filled_x, svp_filled_y = fill_borders_circumference(svp_centered_x, svp_centered_y, 40, tol=1e-5)

    print(f"Punti dopo fill_borders_circumference: {len(svp_filled_x)} punti")

    # ============= ESPANSIONE VERSO ESTERNO (SCALING GEOMETRICO) =============
    plt.figure(figsize=(14, 14))

    # Cerchio casing
    theta_casing = np.linspace(0, 2 * np.pi, 200)
    plt.plot(15.0 * np.cos(theta_casing), 15.0 * np.sin(theta_casing),
             'k-', linewidth=3.5, label='Casing D=30mm', zorder=10)

    # Stella iniziale
    plt.plot(svp_filled_x * 1000, svp_filled_y * 1000, 'b', linewidth=4,
             label='Stella iniziale', zorder=9)

    # Parametri per espansione geometrica
    n_iterations = 8  # 8 linee intermedie
    r_casing = 15.0e-3  # raggio casing in metri

    # Calcolo raggio massimo della stella iniziale
    r_max_stella = np.max(np.hypot(svp_filled_x, svp_filled_y))

    # Fattori di scala da stella a quasi-casing
    scale_factors = np.linspace(1.0, r_casing / r_max_stella * 0.95, n_iterations + 1)[1:]

    print(f"\n{'=' * 70}")
    print(f"SVP INDUSTRIES 5 POINTS - ESPANSIONE GEOMETRICA:")
    print(f"  Raggio max stella: {r_max_stella * 1000:.2f} mm")
    print(f"  Raggio casing: {r_casing * 1000:.2f} mm")
    print(f"  Numero iterazioni: {n_iterations}")
    print(f"  Scale factors: da 1.0 a {scale_factors[-1]:.3f}")
    print(f"{'=' * 70}\n")

    colors = plt.cm.rainbow(np.linspace(0, 1, n_iterations))

    # Espando la geometria con scaling uniforme (invece di burn_surface)
    for i, scale in enumerate(scale_factors):
        # Scala uniformemente tutti i punti rispetto all'origine
        scaled_x = svp_filled_x * scale
        scaled_y = svp_filled_y * scale

        # Plot della geometria scalata
        plt.plot(scaled_x * 1000, scaled_y * 1000,
                 color=colors[i], alpha=0.8, linewidth=2.2, zorder=8 - i * 0.1)

        print(f"  Iterazione {i + 1}: scale={scale:.3f}, r_max={np.max(np.hypot(scaled_x, scaled_y)) * 1000:.2f}mm")

    plt.axis('equal')
    plt.grid(True, alpha=0.3, linestyle=':', linewidth=0.8)
    plt.legend(fontsize=14, loc='upper right', framealpha=0.98, edgecolor='black', fancybox=True)
    plt.title('SVP Industries 5 Points - Burning Progression\n' +
              f'Espansione geometrica uniforme | {n_iterations} iterazioni',
              fontsize=16, weight='bold', pad=20)
    plt.xlabel('Posizione X (mm)', fontsize=14, weight='bold')
    plt.ylabel('Posizione Y (mm)', fontsize=14, weight='bold')
    plt.xlim(-17, 17)
    plt.ylim(-17, 17)
    plt.tight_layout()
    plt.show()

    print(f"\n✓ SVP Industries 5 Points - Visualizzazione completata!")
    print(f"  Linee totali mostrate: {n_iterations + 1} linee")
    print(f"  (1 blu iniziale + {n_iterations} colorate con scaling uniforme)")

    # ============= SVP INDUSTRIES 5 POINTS - Stella a 5 punte =============
    # Parametri stella
    D_int_base = 6.62e-3  # [m] = 6.62 mm
    D_ext = 20.0e-3  # [m] = 20.0 mm

    r_interno = D_int_base / 2  # 3.31 mm
    r_esterno = D_ext / 2  # 10.0 mm

    # Raggio punta arrotondata (95% del raggio esterno per punte meno appuntite)
    r_punta = 0.95 * r_esterno  # 9.5 mm invece di 10.0 mm

    n_points_side = 20  # Più punti per curve più morbide

    # ===== LATO SUPERIORE (da insenatura sinistra a punta) =====
    upper_angles = np.linspace(np.deg2rad(-18), np.deg2rad(0), n_points_side)

    # Transizione CURVA con funzione cubica per lati più arrotondati
    t_upper = np.linspace(0, 1, n_points_side)
    # Funzione cubica per transizione molto morbida e curva
    upper_radii = r_interno + (r_punta - r_interno) * (t_upper ** 2) * (3 - 2 * t_upper)

    upper_points = []
    for angle, radius in zip(upper_angles, upper_radii):
        upper_points.append([radius * np.cos(angle), radius * np.sin(angle)])

    # ===== LATO INFERIORE (da punta a insenatura destra) =====
    lower_angles = np.linspace(np.deg2rad(0), np.deg2rad(18), n_points_side)

    # Transizione CURVA con funzione cubica
    t_lower = np.linspace(0, 1, n_points_side)
    lower_radii = r_punta + (r_interno - r_punta) * (t_lower ** 2) * (3 - 2 * t_lower)

    lower_points = []
    for angle, radius in zip(lower_angles, lower_radii):
        lower_points.append([radius * np.cos(angle), radius * np.sin(angle)])

    # Combino i due lati
    svp_instance = np.array(upper_points + lower_points[1:])

    print(f"SVP INDUSTRIES 5 POINTS - {svp_instance.shape[0]} punti per sezione:")
    print("=" * 70)
    print(f"  Raggio interno (insenature): {r_interno * 1000:.2f} mm")
    print(f"  Raggio punta (arrotondata): {r_punta * 1000:.2f} mm")
    print("=" * 70)

    # Replica 5 volte per creare la stella completa
    svp_points_x, svp_points_y = create_repeated_instance(svp_instance[:, 0], svp_instance[:, 1], 5)
    svp_centered_x, svp_centered_y = translate_figure(svp_points_x, svp_points_y)

    print(f"\nPunti totali dopo replicazione x5: {len(svp_points_x)} punti")

    # Fill con archi circolari
    svp_filled_x, svp_filled_y = fill_borders_circumference(svp_centered_x, svp_centered_y, 40, tol=1e-5)

    print(f"Punti dopo fill_borders_circumference: {len(svp_filled_x)} punti")

    # ============= ESPANSIONE RADIALE VERSO CASING (TUTTE LE PARTI ARRIVANO INSIEME) =============
    plt.figure(figsize=(14, 14))

    # Cerchio casing
    theta_casing = np.linspace(0, 2 * np.pi, 200)
    plt.plot(15.0 * np.cos(theta_casing), 15.0 * np.sin(theta_casing),
             'k-', linewidth=3.5, label='Casing D=30mm', zorder=10)

    # Stella iniziale
    plt.plot(svp_filled_x * 1000, svp_filled_y * 1000, 'b', linewidth=4,
             label='Stella iniziale', zorder=9)

    # Parametri per espansione radiale
    n_iterations = 8  # 8 linee intermedie
    r_casing = 15.0e-3  # raggio casing in metri

    # Calcolo raggi di ogni punto della stella
    r_points = np.hypot(svp_filled_x, svp_filled_y)
    theta_points = np.arctan2(svp_filled_y, svp_filled_x)

    # Progress factors da 0 a 0.95 (95% verso il casing)
    progress_values = np.linspace(0, 0.95, n_iterations + 1)[1:]

    print(f"\n{'=' * 70}")
    print(f"SVP INDUSTRIES 5 POINTS - ESPANSIONE RADIALE UNIFORME AL CASING:")
    print(f"  Raggio casing: {r_casing * 1000:.2f} mm")
    print(f"  Numero iterazioni: {n_iterations}")
    print(f"  Tutte le parti arrivano al casing contemporaneamente")
    print(f"{'=' * 70}\n")

    colors = plt.cm.rainbow(np.linspace(0, 1, n_iterations))

    # Espansione radiale: ogni punto si muove verso r_casing in modo proporzionale
    for i, progress in enumerate(progress_values):
        # Interpolazione lineare: r_new = r_old + (r_casing - r_old) * progress
        # Questo fa sì che ogni punto si muova verso il casing proporzionalmente
        # Le parti interne (r piccolo) si muovono DI PIÙ
        # Le parti esterne (r grande) si muovono DI MENO
        # Tutte arrivano insieme a r_casing quando progress=1.0

        r_new = r_points + (r_casing - r_points) * progress

        # Converti in coordinate cartesiane
        expanded_x = r_new * np.cos(theta_points)
        expanded_y = r_new * np.sin(theta_points)

        # Plot della geometria espansa
        plt.plot(expanded_x * 1000, expanded_y * 1000,
                 color=colors[i], alpha=0.8, linewidth=2.2, zorder=8 - i * 0.1)

        r_min_new = np.min(r_new) * 1000
        r_max_new = np.max(r_new) * 1000
        print(
            f"  Iter {i + 1}: progress={progress:.3f}, r_min={r_min_new:.2f}mm, r_max={r_max_new:.2f}mm, diff={r_max_new - r_min_new:.2f}mm")

    plt.axis('equal')
    plt.grid(True, alpha=0.3, linestyle=':', linewidth=0.8)
    plt.legend(fontsize=14, loc='upper right', framealpha=0.98, edgecolor='black', fancybox=True)
    plt.title('SVP Industries 5 Points - Burning Progression\n' +
              f'Espansione radiale uniforme verso casing | {n_iterations} iterazioni',
              fontsize=16, weight='bold', pad=20)
    plt.xlabel('Posizione X (mm)', fontsize=14, weight='bold')
    plt.ylabel('Posizione Y (mm)', fontsize=14, weight='bold')
    plt.xlim(-17, 17)
    plt.ylim(-17, 17)
    plt.tight_layout()
    plt.show()

    print(f"\n✓ SVP Industries 5 Points - Visualizzazione completata!")
    print(f"  Linee totali mostrate: {n_iterations + 1} linee")
    print(f"  (1 blu iniziale + {n_iterations} colorate)")
    print(f"  Tutte le parti della stella arrivano al casing insieme!")

# ============= SVP INDUSTRIES WAGON WHEEL - 10 lobi con forma corretta =============
# Parametri wagon wheel
D_int_base = 6.62e-3  # [m] = 6.62 mm (raggio nelle valli)
D_ext = 20.0e-3  # [m] = 20.0 mm (raggio massimo lobi)
D_casing = 26.5e-3  # [m] = 26.5 mm

r_interno = D_int_base / 2  # 3.31 mm
r_esterno = D_ext / 2  # 10.0 mm
r_casing = D_casing / 2  # 13.25 mm

# Numero di lobi
n_lobi = 10

print(f"SVP INDUSTRIES WAGON WHEEL - {n_lobi} lobi:")
print("=" * 70)
print(f"  Raggio interno (valli): {r_interno * 1000:.2f} mm")
print(f"  Raggio esterno (lobi): {r_esterno * 1000:.2f} mm")
print(f"  Raggio casing: {r_casing * 1000:.2f} mm")
print("=" * 70)

# Creo UN LOBO e lo replico
# Ogni lobo è definito da angoli che vanno da -angolo_lobo/2 a +angolo_lobo/2
angolo_per_lobo = 2 * np.pi / n_lobi  # 36° per lobo
frazione_valle = 0.3  # 30% dell'angolo è valle (r_interno)
frazione_transizione = 0.35  # 35% dell'angolo è transizione
frazione_lobo = 0.35  # 35% dell'angolo è lobo pieno (r_esterno)

# Definisco angoli per UNA sezione (un lobo)
n_points_per_lobo = 50
theta_lobo = np.linspace(-angolo_per_lobo / 2, angolo_per_lobo / 2, n_points_per_lobo)

# Funzione raggio per UN lobo
# - Parte centrale: valle a r_interno
# - Transizione: crescita morbida
# - Parte esterna: lobo a r_esterno
# - Transizione: decrescita morbida
# - Ritorno a valle

radii_lobo = np.zeros(n_points_per_lobo)

for i, theta in enumerate(theta_lobo):
    # Normalizzo theta da -1 a +1
    t = theta / (angolo_per_lobo / 2)  # t va da -1 a +1
    t_abs = abs(t)

    if t_abs < frazione_valle:
        # Valle centrale: raggio interno
        radii_lobo[i] = r_interno
    elif t_abs < frazione_valle + frazione_transizione:
        # Transizione: smooth crescita verso lobo
        progress = (t_abs - frazione_valle) / frazione_transizione
        # Uso smoothstep per transizione morbida
        smooth = progress * progress * (3 - 2 * progress)
        radii_lobo[i] = r_interno + (r_esterno - r_interno) * smooth
    else:
        # Lobo esterno: raggio massimo con piccola curvatura
        progress = (t_abs - frazione_valle - frazione_transizione) / frazione_lobo
        # Leggera riduzione alle estremità per forma arrotondata
        curvatura = 1.0 - 0.1 * progress * progress
        radii_lobo[i] = r_esterno * curvatura

# Creo coordinate per UN lobo
x_lobo = radii_lobo * np.cos(theta_lobo)
y_lobo = radii_lobo * np.sin(theta_lobo)

# Replico il lobo n_lobi volte
all_x = []
all_y = []

for i in range(n_lobi):
    angolo_rotazione = i * angolo_per_lobo
    cos_rot = np.cos(angolo_rotazione)
    sin_rot = np.sin(angolo_rotazione)

    # Ruoto il lobo
    x_rot = x_lobo * cos_rot - y_lobo * sin_rot
    y_rot = x_lobo * sin_rot + y_lobo * cos_rot

    all_x.extend(x_rot[:-1])  # Escludo ultimo punto per evitare duplicati
    all_y.extend(y_rot[:-1])

wagon_x = np.array(all_x)
wagon_y = np.array(all_y)

print(f"\nPunti wagon wheel: {len(wagon_x)} punti ({n_lobi} lobi)")

# ============= ESPANSIONE RADIALE VERSO CASING =============
fig = plt.figure(figsize=(14, 14))

# Cerchio casing
theta_casing = np.linspace(0, 2 * np.pi, 200)
plt.plot(r_casing * 1000 * np.cos(theta_casing), r_casing * 1000 * np.sin(theta_casing),
         'k-', linewidth=3.5, label=f'Casing D={D_casing * 1000:.1f}mm', zorder=10)

# Wagon wheel iniziale
plt.plot(wagon_x * 1000, wagon_y * 1000, 'b', linewidth=4,
         label='Wagon Wheel iniziale', zorder=9)

# Parametri per espansione radiale
n_iterations = 8

# Calcolo raggi
r_points = np.hypot(wagon_x, wagon_y)
theta_points = np.arctan2(wagon_y, wagon_x)

# Progress factors
progress_values = np.linspace(0, 0.95, n_iterations + 1)[1:]

print(f"\n{'=' * 70}")
print(f"SVP WAGON WHEEL - ESPANSIONE RADIALE:")
print(f"  Numero iterazioni: {n_iterations}")
print(f"{'=' * 70}\n")

colors = plt.cm.rainbow(np.linspace(0, 1, n_iterations))

# Espansione radiale
for i, progress in enumerate(progress_values):
    r_new = r_points + (r_casing - r_points) * progress

    expanded_x = r_new * np.cos(theta_points)
    expanded_y = r_new * np.sin(theta_points)

    plt.plot(expanded_x * 1000, expanded_y * 1000,
             color=colors[i], alpha=0.8, linewidth=2.2, zorder=8 - i * 0.1)

    r_min_new = np.min(r_new) * 1000
    r_max_new = np.max(r_new) * 1000
    print(f"  Iter {i + 1}: r_min={r_min_new:.2f}mm, r_max={r_max_new:.2f}mm")

plt.axis('equal')
plt.grid(True, alpha=0.3, linestyle=':', linewidth=0.8)
plt.legend(fontsize=14, loc='upper right', framealpha=0.98, edgecolor='black', fancybox=True)

plt.title('SVP Industries Wagon Wheel - Burning Progression\n10 lobi con valli e transizioni morbide',
          fontsize=18, weight='bold', pad=25)

plt.xlabel('Posizione X (mm)', fontsize=14, weight='bold')
plt.ylabel('Posizione Y (mm)', fontsize=14, weight='bold')

axis_limit = r_casing * 1000 * 1.15
plt.xlim(-axis_limit, axis_limit)
plt.ylim(-axis_limit, axis_limit)

plt.subplots_adjust(top=0.94)
plt.tight_layout(rect=[0, 0, 1, 0.96])

output_path = 'svp_wagon_wheel_10lobi_burning.png'
plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
print(f"\n✓ Immagine salvata in: {output_path}")

plt.show()

print(f"\n✓ SVP Wagon Wheel completata!")